services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname?sslmode=disable
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=wordwiz
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
